### ISSUE TITLE
create a version included in component

### ISSUE THREAD

**Issue by jonathanong** [pirxpilot/component-shrinkwrap#5]
how do you feel about that? i added `component pin`, but i still want a shrinkwrap of all my deps' deps.

you'd have to update this with `component-resolver`

**Comment by timaschew** [comment]
FYI: shrinkwrapper for component 1.1.* https://github.com/componentjs/shrinkwrapper

**Comment by pirxpilot** [comment]
@timaschew  - you sure you don't want `component-shrinkwrap` npm name? you could start releasing > 1.0.0

**Comment by timaschew** [comment]
oh, yes that would be fine :)

**Comment by pirxpilot** [comment]
OK - @timaschew - I added you to component-shrinkwrap owners
Feel free to rename component-shrinkwrapper -> component-shrinkwrap
I'll update readme here with the link to 1.x compatible version once you do that.
The only thing I ask is that you don't release any 0.x versions for obvious reasons ;-) I might release 0.x if I need to fix something but that's not very likely at this point.
And thank you for all the work on component.

**Comment by timaschew** [comment]
Thank you.

I know it's a common way to start with 0.*  
To be honest, I just run `npm init` and the default version was 1.0.0 ;)
But starting with 1.0.0 is maybe also more clear that it belongs to component 1.* and not to 0.*

And if you look at semver description:
> 4) Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
5) Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

So if the API will change, we can just bump to 2.0.0

**Comment by timaschew** [comment]
okay, renamed the module to component-shrinkwrap and published to npm
